# Generated by Django 2.0 on 2020-01-17 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='location',
            new_name='neighbourhood',
        ),
    ]
